In [4]:
import pandas as pd

In [5]:
df1 = pd.read_csv(r"C:\Users\hp\chatbot_health\data_sets\intent\arabe_darija.csv")
df2=pd.read_csv(r"C:\Users\hp\chatbot_health\data_sets\intent\arabizi_intent.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\hp\\chatbot_health\\data_sets\\intent\\arabe_darija.csv'

In [9]:
df_final = pd.concat([df1, df2]).sample(frac=1).reset_index(drop=True)
df_final.to_csv("intent_final.csv", index=False)

NameError: name 'df1' is not defined

In [8]:
df_final.head()

NameError: name 'df_final' is not defined

In [14]:
print(df_final.shape)
print(df_final["intent"].value_counts())
print(df_final.isnull().sum())

(1049, 3)
intent
demande_urgence           150
remboursement_mutuelle    150
description_symptome      150
demande_posologie         150
demande_consultation      150
demande_medicament        150
demande_prix              149
Name: count, dtype: int64
text        0
intent      0
language    0
dtype: int64

In [6]:
df_1=pd.read_csv(r"C:\Users\hp\chatbot_health\backend\datasets\intent\aef_intet.csv")
print(df_1["intent"].value_counts())

intent
demande_medicament        210
demande_consultation      168
demande_urgence           168
demande_prix              168
demande_posologie         168
remboursement_mutuelle    168
description_symptome      168
pharmacie_garde            84
intent                      2
Name: count, dtype: int64

In [3]:
df11 = df_1[df_1['intent'] != 'pharmacie_garde']
df11.to_csv("intent_final2.csv", index=False)

NameError: name 'df_1' is not defined

In [8]:
df11["intent"].value_counts()

intent
demande_medicament        210
demande_consultation      168
demande_urgence           168
demande_prix              168
demande_posologie         168
remboursement_mutuelle    168
description_symptome      168
intent                      2
Name: count, dtype: int64

In [9]:
df11.head()

                                        phrase                intent language
0  I need an appointment with the doctor today  demande_consultation  english
1               Can you book a dentist for me?  demande_consultation  english
2      Pediatrician availability for tomorrow?  demande_consultation  english
3              I'd like to see a cardiologist.  demande_consultation  english
4       How to schedule a dermatologist visit?  demande_consultation  english

In [10]:
df_shuffled = df11.sample(frac=1, random_state=42)
df_shuffled = df_shuffled.reset_index(drop=True)
df_shuffled.head()

                       phrase                intent  language
0               طبيب المفاصل.  demande_consultation     arabe
1         Voir le chirurgien.  demande_consultation  francais
2  Heart attack, send medics!       demande_urgence   english
3               tbib d nboula  demande_consultation   arabizi
4        القلب كيضرب بالزربة.  description_symptome     arabe

In [11]:
df_shuffled.to_csv("intent_final2.csv", index=False)

In [2]:
intent_rows = df11[df11['label'] == 'intent']
print(f"Nombre de lignes 'intent' dans train : {len(intent_rows)}")
print(intent_rows.head())

NameError: name 'df11' is not defined

In [16]:
df_clean=pd.read_csv(r"C:\Users\hp\chatbot_health\backend\datasets\intent\intent_final2.csv")
print(df_clean["intent"].value_counts())

intent
demande_medicament        210
demande_consultation      168
demande_urgence           168
description_symptome      168
demande_posologie         168
remboursement_mutuelle    168
demande_prix              168
intent                      2
Name: count, dtype: int64

In [18]:
# Drop les 2 lignes "intent" dans df_clean
df_clean = df_clean[df_clean['intent'] != 'intent'].copy()

# Vérifier
print(df_clean['intent'].value_counts())

intent
demande_medicament        210
demande_consultation      168
demande_urgence           168
description_symptome      168
demande_posologie         168
remboursement_mutuelle    168
demande_prix              168
Name: count, dtype: int64

In [19]:
df_clean['intent'].value_counts()

intent
demande_medicament        210
demande_consultation      168
demande_urgence           168
description_symptome      168
demande_posologie         168
remboursement_mutuelle    168
demande_prix              168
Name: count, dtype: int64

In [21]:
df_clean.to_csv("intent_final22.csv", index=False)